all:
  children:
    big_ips:
      hosts:
        your-bigip-hostname-here:
            ansible_connection: local
            bigip_provider:
              server: "{{ inventory_hostname }}"
              user: "admin"
              password: "your_password_here"
              validate_certs: false
              server_port: 443