all:
  children:
    big_ips:
      hosts:
        your_bigip_host_name_here:
            ansible_connection: local
            bigip_provider:
              server: "{{ inventory_hostname }}"
              user: admin
              password: yourpasswordhere
              validate_certs: false
              server_port: 443